import Head from 'next/head'
import CategoryContainer from '../components/category-components/CategoryContainer'
import Hero from '../components/main-components/Hero'
import ProductTrending from '../components/product-components/ProductTrending'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shop</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <CategoryContainer />
      <ProductTrending />
    </div>
  )
}
